### ISSUE TITLE
Dashes in branch names are being split on the merge button

### ISSUE THREAD

**Issue by calebmeyer** [AstrickHarren/git-merge#1]
![image](https://user-images.githubusercontent.com/3342777/60034726-e55b9a00-9670-11e9-88cc-83f04f183a3b.png)

This repo has exactly two branches, `master` and `test-dashes-in-name`. I totally understand that this is 0.3, just wanted to point this out to maybe help you in the right direction.

**Comment by AstrickHarren** [comment]
Believe it is fixed in the newest release. Thanks a lot for the report!!! Closing this issue in 1 day. 

> Developer: Actually this package is designed to temporarily assist atom/Github to merge since it does not provide the function yet, and it was initially designed for myself. Therefore I am sorry there was no thorough alpha test, and personally I am one of its testers. However I will still fix every bug I encounter or am informed. Thanks for understanding.
