### ISSUE TITLE
Version in Atom is still at 0.2.0

### ISSUE THREAD

**Issue by roblan11** [AstrickHarren/git-merge#3]
https://atom.io/packages/git-merge

The title pretty much sais it. The version for download on the Atom Package Installer contains a couple bugs that you have fixed already.

**Comment by threepistons** [comment]
@roblan11 Do you know if there is a method for "sideloading" the newer version without using the built-in Atom package manager?

**Comment by roblan11** [comment]
@threepistons Sure. First make sure you have apm (Atom Package Manager) installed. This should automatically happen when you install atom on your system. Simply open the terminal / command prompt / ... and type `apm`.
Then download the code as a zip archive and extract it somewhere. go to that folder with your terminal and type `apm link`. That should install the package.

**Comment by roblan11** [comment]
If you really don't want to use apm, you can install the package within atom, open the plugin page in atom and you should get a "View Code" button near the top right. From there you can copy the code from git into the files and you should be good to go.

**Comment by threepistons** [comment]
Thanks.

**Comment by AstrickHarren** [comment]
Think just solved that. close #3

**Comment by AstrickHarren** [comment]
Think just published the new version. Close #3
